%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 405.6384738851233
Camera.fy: 405.588335378204
Camera.cx: 189.9054317917407
Camera.cy: 139.9149578253755

Camera.k1: -0.3670656233416921 
Camera.k2: 0.203001968694465
Camera.p1: 0.003336917744124004
Camera.p2: -0.000487426354679637

# Camera frames per second 
Camera.fps: 5.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid (min->1 / max->2)     
ORBextractor.scaleFactor: 1.4

# ORB Extractor: Number of levels in the scale pyramid  
ORBextractor.nLevels: 4

#Detector threshold : 
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast 
# (Fast: min = 1)               
ORBextractor.iniThFAST: 5 
ORBextractor.minThFAST: 1

# Stretching Tolerance :
# ORBextractor.nTolerance: 0

Image.PreProcessing: 0

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize: 2
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2
Viewer.ViewpointX: 0
Viewer.ViewpointY: -10
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000

