%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 869.57153589
Camera.fy: 868.1183944
Camera.cx: 372.50825442
Camera.cy: 251.95109693

Camera.k1: 0.02273871
Camera.k2: 0.01916195
Camera.p1: -0.00190073
Camera.p2: -0.00053882

# Camera frames per second 
Camera.fps: 20.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Perform Loop Closures ?
Camera.UseLoopClosure: 0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid (min->1 / max->2)     
ORBextractor.scaleFactor: 1.4

# ORB Extractor: Number of levels in the scale pyramid  
ORBextractor.nLevels: 8

#Detector threshold : 
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast 
# (Fast: min = 1)               
ORBextractor.iniThFAST: 5 
ORBextractor.minThFAST: 1

# Stretching Tolerance :
# ORBextractor.nTolerance: 0

Image.PreProcessing: 0

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize:2
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2
Viewer.ViewpointX: 0
Viewer.ViewpointY: -10
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000

